# Generated by Django 3.2.25 on 2025-12-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
